version: '3'
services:
  oli:
    image: dannyquist/oli-mmdvm
    user: node
    ports:
      - "3000:3000"
    volumes:
      - oli_conf:/oli/conf
      - oli_log:/oli/log
  mmdvmhost:
    image: dannyquist/oli-mmdvm
    user: root
    devices:
      - "/dev/ttyAMA0:/dev/ttyAMA0"
    volumes:
      - oli_conf:/oli/conf
      - oli_log:/oli/log
    command: /oli/MMDVMHost /oli/conf/MMDVM.ini
volumes:
  oli_conf:
  oli_log:
